#!/usr/bin/env bash
# Displays information about subdomains

	if [ "$#" -eq 1 ]
	then
		for i in "www" "lb-01" "web-01" "web-02"
		do
			string=$(dig +noall +answer "$i.$1")
			record=$(echo "$string"| awk '{ print $4 }')
			destination=$(echo "$string"| awk '{ print $5 }')
			echo "The subdomain $i is a $record record and points to $destination"
		done
		exit 1
	fi
	for var in "$@"
	do
		if [ "$1" != "$var" ]
		then
			dig +noall +answer "$var.$1"
		fi
	done

