#!/usr/bin/env bash
# Transfers a file form our client to a server
# Accepts 4 parameters - path to the file, ip to transfer to, username scp
# connects with, path to the ssh key the scp uses

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
