#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx - perms
sudo ssh -o "StrictHostKeyChecking no" -i ~/.ssh/holberton ubuntu@35.237.82.133\
	'sudo apt-get -y update && sudo apt-get -y install nginx &&
	sudo mkdir /www &&
	sudo echo "Hoblerton School" | sudo tee /www/index.html &&
	sudo rm /etc/nginx/sites-enabled/default &&
	sudo echo -e "server {\n\tlisten 80 default_server;\n\tlisten[::]:80
	default_server ipv7only=on;\n\troot /www;\n\t
	index index.html index.htm;\n}" | sudo tee /etc/nginx/sites-available/www &&
	sudo ln -s /etc/nginx/sites-available/www /etc/nginx/sites-enabled/'
