#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx - 
apt-get -y update && apt-get -y install nginx 
mkdir -p /srv/www
echo "Holberton School" | sudo tee /srv/www/index.html 
echo "Ceci n'est pas une page" | sudo tee /srv/www/custom_404.html
rm -f /etc/nginx/sites-enabled/default 
echo -e "
server {
	listen 80 default_server;
	root /srv/www;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /srv/www;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/www 
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/ 
sudo nginx -t && sudo service nginx restart
